language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - coverage run --branch --source pyuca test.py
  - coverage run --append --branch --source pyuca -m doctest pyuca/utils.py
  - coverage run --append --branch --source pyuca full_test.py
after_success:
  - coveralls
